// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SDKTest.Data.DataAccess;

namespace SDKTest.Data.DataAccess.Migrations
{
    [DbContext(typeof(SDKTestDbContext))]
    [Migration("20200504182009_AddTrajectsFix")]
    partial class AddTrajectsFix
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SDKTest.Data.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("LastName");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("SDKTest.Data.Entities.Traject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Distance");

                    b.Property<double>("Duration");

                    b.Property<Guid?>("EmployeeId");

                    b.Property<double>("FinalLatitude");

                    b.Property<double>("FinalLongitude");

                    b.Property<double>("InitialLatitude");

                    b.Property<double>("InitialLongitude");

                    b.Property<bool>("IsFinished");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Trajects");
                });

            modelBuilder.Entity("SDKTest.Data.Entities.Traject", b =>
                {
                    b.HasOne("SDKTest.Data.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");
                });
#pragma warning restore 612, 618
        }
    }
}
